#! /bin/sh
(cd src/GLPK; 
  if test -f Makefile; then
    make distclean || true
    make distclean SUBDIRS= || true
  fi)
(cd src/GLPK;
  if test -f libglpk.a; then
    rm -f *.o *.a minisat/*.o amd/*.o colamd/*.o zlib/*.o
  fi)
rm -f config.* autom4te.cache src/GLPK.ts src/Makevars 
exit 0
